### ISSUE TITLE
这想法不错，我的项目加几行代码应该很快

### ISSUE THREAD

**Issue by abse4411** [Mr0KL/renpy-mtool-#1]
感觉可以把你的这个功能集成到这个[项目](https://github.com/abse4411/projz_renpy)里面，增加导出json和导入json的功能。

**Comment by Mr-small-2-six** [comment]
我是代码小白单纯希望抛砖引玉，你可以集成你的项目里完全没问题
本来就是希望自己翻译想玩的游戏，有人可以完善这些功能就更好
